name: Composer

on: [ push ] 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
#      - name: Setup PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      # Runs a single command using the runners shell
      - run: composer install -n --no-progress --no-dev --no-scripts --optimize-autoloader
